### PR TITLE
Fix Edge Body Locking Issue #101

### PR DESCRIPTION
**Pull request by erwstout**
This change sets the body overflow to `unset` when scroll locking is disabled. Currently on edge, when scroll locking is set to `true` and the modal is closed, scrolling is not restored.

```js
// new 
Object.assign(body.style, { overflow: 'unset', height: 'initial' });

// old
Object.assign(body.style, { overflow: 'initial', height: 'initial' });
```

### CODE REVIEW

**Comment by kalpeshsingh** [comment]
Hi @erwstout ,

Thanks for taking time and submitting PR. It helps us alot. 

Seems like `unset` doesn't have support in from IE6 - IE11. We should at least aim for IE11.
Do you have anything in mind to cover IE11 too?

**Comment by erwstout** [comment]
Sure, let me see what I can come up with.

**Comment by erwstout** [comment]
@kalpeshsingh I updated this to just use empty strings, which removes the style properties all together on close. Tested in IE11 and it fixes the issue. 

```js
scrollBehaviour (toggle) {
      if (!this.config.disableScroll) return
      const body = document.querySelector('body')
      switch (toggle) {
        case 'enable':
          Object.assign(body.style, {overflow: '', height: ''})
          break
        case 'disable':
          Object.assign(body.style, {overflow: 'hidden', height: '100vh'})
          break
        default:
      }
    }
```

**Comment by ajschmidt8** [comment]
thanks for the fix, @erwstout .
can we get this merged and released? @ghosh @kalpeshsingh

**Comment by erwstout** [comment]
Any idea if this will get merged?

**Comment by joshangehr** [comment]
Would also like to see this merged. I've been doing it manually for each project. Any way we can help?

**Comment by zebapy** [comment]
Also looking for this fix. I'll have to manually do this by adding the style changes in `onShow/onClose`

**Pull request merged**
