### PR TITLE
Fix window ref error while SSR

### PR DESCRIPTION
**Pull request by ibn-akbar**
Fix "ReferenceError: window is not defined" while running SSR.

### CODE REVIEW

**Comment by ibn-akbar** [comment]
@ghosh This issue is blocking us from using Micromodal with Vite.
Can you please merge the PR if there's no issue?

**Comment by benaltair** [comment]
Was going to submit the same PR. This would fix #311 as well I believe. I'm getting the same error on [Svelte Kit](https://kit.svelte.dev/) where `window` trips us SSR.
```
ReferenceError: window is not defined
    at /node_modules/micromodal/dist/micromodal.es.js:437:1
    at instantiateModule (D:\Github\conference\node_modules\vite\dist\node\chunks\dep-66eb515d.js:69030:166)
```
See more details here:
https://github.com/ghosh/Micromodal/issues/311#issuecomment-817027551

**Comment by benaltair** [comment]
Hi @ghosh is it possible to give some attention to this PR? Should be simple to check, single line.

**Comment by HongPong** [comment]
The test errors are like
```
Error: Unable to process command '::set-env name=CI::1' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: Unable to process command '::set-env name=CYPRESS_CACHE_FOLDER::/home/runner/.cache/Cypress' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
and
```
Error: Unable to process command '::set-env name=CYPRESS_CACHE_FOLDER::/home/runner/.cache/Cypress' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
I'm not familiar enough to say what is best here.

**Comment by ibn-akbar** [comment]
@HongPong The old method of setting environment variables for Github actions has been deprecated. Its causing the build test to fail.

**Comment by ibn-akbar** [comment]
@HongPong Great. I think your PR (#442) has fixed the build issue.
But I don't think it'll get merged anytime soon. It seems @ghosh is not actively maintaining Micromodal.

**Comment by HongPong** [comment]
@ibn-akbar  i see activity on the "next" branch so I am a bit more optimistic than I was earlier. In any case I am trying to solve a problem for a client so I'll make PRs as I go along regardless.

**Comment by dessalines** [comment]
Anyone maintaining a fork of this now?

**Pull request merged**
