### PR TITLE
Adding an option to disable esc.

### PR DESCRIPTION
**Pull request by ugurcanbulut**
Adding an option called `disableEsc` for being able to prevent closing modal on `ESC` keypress.

### CODE REVIEW

**Comment by MykalMachon** [comment]
Seconding this PR! 
Would be extremely useful for me in a few places (i.e mandatory age confirmation popups for certain e-com sites)

**Comment by seb3s** [comment]
I also need this feature for my usage.
Please consider integrating it.
Thanks a lot

**Comment by abhijitbcob** [comment]
Really need this feature me too!

**Comment by kendagriff** [comment]
Yes, adding another bump for this!

**Comment by Voltra** [comment]
Re-up !

**Pull request closed without merging**
