### PR TITLE
Fix `MicroModal.close` now closes the modal based on the ID passed

### PR DESCRIPTION
**Pull request by roebuk**
This is the initial pass at fixing #112 . Let me know if anything needs a tweak to be a better fit for the project :)

It also enables development to be done on a Windows environment with the addition of the `cross-env` library.

### CODE REVIEW

**Comment by pomartel** [comment]
I also ran into that bug. The documentation states that a modal can be closed by its id but it's not the case.

Also, the `activeModal` variable is set in the the `show` function. It should be set in the `showModal` function instead. This way a modal instantiated with the `data-micromodal-trigger` could also be closed programatically.

**Comment by donbot-inc** [comment]
Reference #113

**Comment by ghosh** [comment]
Thank you @roebuk. Appreciate you writing the tests as well. Cheers!

**Comment by caiotarifa** [comment]
I still get an error...

```
TypeError: null is not an object (evaluating 'activeModal.closeModalById')
```

I am using Turbolinks.

``` javascript
import MicroModal from 'micromodal'

document.addEventListener('turbolinks:load', function () {
  MicroModal.init()
})

document.addEventListener('turbolinks:before-cache', function () {
  MicroModal.close('modal-id')
})
```

**Comment by NibblyPig** [comment]
The issue linked to this has been closed but we're having the exact same problem, either there is still an issue or the fix never made it into the latest version for download from the micromodal website.

**Comment by ghosh** [comment]
Yes, it’s not released yet. Closing a few other issues as well. Will update soon.

**Comment by ksromero** [comment]
Is this issue has been fixed?

**Comment by patrickjsmirnov** [comment]
@ksromero I still have this problem.

**Comment by Ahrry** [comment]
HI @ghosh ! When this PR will be released ?

**Comment by raviobra12** [comment]
i'm still having this issue, has anyone got a working alternative?

**Comment by yodnoralov** [comment]
any update?

**Pull request merged**
